//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineRWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancel
    {
        public int CancelNo { get; set; }
        public Nullable<int> TicketNo { get; set; }
        public string FlightNo { get; set; }
        public string Fname { get; set; }
        public string FromPlace { get; set; }
        public string ToPlace { get; set; }
        public string DOJ { get; set; }
        public string Depature { get; set; }
    }
}
